spring:
  profiles:
    active: stage

---
spring:
  profiles: dev
message: Hello from DEV environemnt and the current time is
---
spring:
  profiles: stage
message: Hello from STAGE environemnt and the current time is
---
spring:
  profiles: prod
message: Hello from PROD environemnt and the current time is
---